apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: mongtorydiary
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mongtorydiary
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 30081
      targetPort: http
      nodePort: 30081
