apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: mongtorydiary
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mongtorydiary
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 30080
      targetPort: http
      nodePort: 30080
