apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/name: mongtorydiary
    app.kubernetes.io/component: db
spec:
  selector:
    app.kubernetes.io/name: mongtorydiary
    app.kubernetes.io/component: db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
