apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
  labels:
    app.kubernetes.io/name: mongtorydiary
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
