namespace: mongtorydiary

resources:
- namespace.yaml
- ../../base

images:
- name: ghcr.io/yeominsoo/mongtorydiary-backend
  newName: ghcr.io/yeominsoo/mongtorydiary-backend
  newTag: eea36ed77979db5a07d8ae94cc41abe9b17aa0fa
- name: ghcr.io/yeominsoo/mongtorydiary-frontend
  newName: ghcr.io/yeominsoo/mongtorydiary-frontend
  newTag: eea36ed77979db5a07d8ae94cc41abe9b17aa0fa
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
