namespace: mongtorydiary

resources:
- namespace.yaml
- ../../base

images:
- name: ghcr.io/yeominsoo/mongtorydiary-backend
  newName: ghcr.io/yeominsoo/mongtorydiary-backend
  newTag: b93536305a09a79a1a3a34e38bf6593107ca292d
- name: ghcr.io/yeominsoo/mongtorydiary-frontend
  newName: ghcr.io/yeominsoo/mongtorydiary-frontend
  newTag: b93536305a09a79a1a3a34e38bf6593107ca292d
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
