namespace: mongtorydiary

resources:
- namespace.yaml
- ../../base

images:
- name: ghcr.io/yeominsoo/mongtorydiary-backend
  newName: ghcr.io/yeominsoo/mongtorydiary-backend
  newTag: 663b73fd66fffe6bce44124a26d832988932e669
- name: ghcr.io/yeominsoo/mongtorydiary-frontend
  newName: ghcr.io/yeominsoo/mongtorydiary-frontend
  newTag: 663b73fd66fffe6bce44124a26d832988932e669
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
